export const fieldMappings = [
  {
    field: 'gender',
    map: {
      'nữ': 'F',
      'phụ nữ': 'F',
      'gái': 'F',
      'con gái': 'F',
      'Con gái': 'F',
      'Con Gái': 'F',
      'cái': 'F',
      'Cái': 'F',
      'NỮ': 'F',
      'Nữ': 'F',
      'Phụ Nữ': 'F',
      'Phụ nữ': 'F',
      'Female': 'F',
      'FEMALE': 'F',
      'Woman': 'F',
      'WOMAN': 'F',
      'female': 'F',
      'f': 'F',
      'F': 'F',
      'femal': 'F', // Handle potential typo
      'woman': 'F',
      'nam': 'M',
      'đàn ông': 'M',
      'trai': 'M',
      'con trai': 'M',
      'Đực': 'M',
      'đực': 'M',
      'đực rựa': 'M',
      'Đực rựa': 'M',
      'male': 'M',
      'm': 'M',
      'man': 'M',
      'M': 'M',
      'NAM': 'M',
      'Nam': 'M',
      'Đàn Ông': 'M',
      'Đàn ông': 'M',
      'Trai': 'M',
      'Con Trai': 'M',
      'MALE': 'M',
      'Male': 'M',
      'Man': 'M',
      'MAN': 'M',
    }
  },
  {
    field: 'city'
  }
  // Add more objects for city, category, etc. here later
];

export const vietnamProvinces = [
  "An Giang",
  "Bà Rịa – Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái"
]; 